label variable ResponseId "Qualtrics internal ID "
label variable choiceofperson "Contin. choice num 1-8 "
label variable choice "Choice number "
label variable best "1=Preferred policy "
label variable popwt "Pop weight: 50 CA, 20 OR, 30 WA "
label variable mabsdeaths "Absolute deaths/mo/50k "
label variable mabscases "Absolute cases/mo/50k "
label variable feduinoneavcost "Avg. hhld cost for county (federal UI = 0) "
label variable feduianyavcost "Avg. hhld cost for county (federal UI > 0) "
label variable feduinoneunempl "Unempl rate for county (federal UI = 0) "
label variable feduianyunempl "Unempl rate for county (federal UI > 0) "
label variable rule1 "Grocery, essential retail "
label variable rule2 "Non-essential retail "
label variable rule3 "Schools, daycare "
label variable rule4 "Parks, outdoor sports "
label variable rule5 "Gyms, indoor sports "
label variable rule6 "Theaters, concert halls "
label variable rule7 "Restaurants, bars, clubs "
label variable rule8 "Meetings, religious services "
label variable rule9 "Assisted living facilities "
label variable rule10 "Universities, colleges "
label variable statquo "1=Status quo alternative "
label variable RPmabsdeaths "Absolute deaths/mo/50k $\times$ Response propensity"
label variable RPmabscases "Absolute cases/mo/50k $\times$ Response propensity"
label variable RPfeduinoneavcost "Avg. hhld cost for county (federal UI = 0) $\times$ Response propensity"
label variable RPfeduianyavcost "Avg. hhld cost for county (federal UI > 0) $\times$ Response propensity"
label variable RPfeduinoneunempl "Unempl rate for county (federal UI = 0) $\times$ Response propensity"
label variable RPfeduianyunempl "Unempl rate for county (federal UI > 0) $\times$ Response propensity"
label variable RPrule1 "Grocery, essential retail $\times$ Response propensity"
label variable RPrule2 "Non-essential retail $\times$ Response propensity"
label variable RPrule3 "Schools, daycare $\times$ Response propensity"
label variable RPrule4 "Parks, outdoor sports $\times$ Response propensity"
label variable RPrule5 "Gyms, indoor sports $\times$ Response propensity"
label variable RPrule6 "Theaters, concert halls $\times$ Response propensity"
label variable RPrule7 "Restaurants, bars, clubs $\times$ Response propensity"
label variable RPrule8 "Meetings, religious services $\times$ Response propensity"
label variable RPrule9 "Assisted living facilities $\times$ Response propensity"
label variable RPrule10 "Universities, colleges $\times$ Response propensity"
label variable RPstatquo "1=Status quo alternative $\times$ Response propensity"
label variable lassorpfl "Response propensity"
label variable alt "Alternative number "
label variable caseid "Arbitrary case id "
